### ISSUE TITLE
New Steam update broke the UI

### ISSUE THREAD

**Issue by HairyMilkshakes** [badanka/Compact#51] opened 2023-02-01 21:36 UTC
After today's update.

**Comment by Painkiller998** [comment] 2023-02-02 01:26
x2 :C

**Comment by SudosFTW** [comment] 2023-02-02 06:49
This issue is a duplicate of #50 but now on release and not beta.

**Comment by HairyMilkshakes** [comment] 2023-02-02 06:54
> This issue is a duplicate of #50 but now on release and not beta.

Thanks for letting me know I'll check it out.

**Comment by HairyMilkshakes** [comment] 2023-03-22 00:21
A fix was posted here: https://github.com/sthellen/Compact/ but seems to be broken again by yet another update today.

**Comment by badanka** [comment] 2023-04-07 13:29
[Should be fixed now, I just released 1.6.70.](https://github.com/badanka/Compact/releases/tag/1.6.70)

**Closed as completed by badanka** 2023-04-07 13:29 UTC
Labels: beta/non-compatibility
